name: Sync fork with upstream

on:
  workflow_dispatch: # on button click
#  schedule:
#    - cron: '*/30 * * * *' # every 30 minutes

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync latest commits from upstream repo
      run: |
        ls -la
        ls -la ${GITHUB_WORKSPACE}
        ${GITHUB_WORKSPACE}/.github/scripts/sync-fork.sh lassekongo83/adw-gtk3 main:synctest
      env:
        # URL of gitHub public upstream repo
        upstream_repo: "https://github.com/lassekongo83/adw-gtk3.git"
        # Branch to merge from upstream (defaults to downstream branch)
        upstream_branch: main
        # Branch to merge into downstream
        downstream_branch: synctest
